In [13]:
import numpy as np
import matplotlib.pyplot as plt
import nest

In [14]:
data_path = "data/"

data = np.loadtxt(data_path + "network_structure.dat")

ordered_ids = np.argsort(data[:,0])
data_ordered = data[ordered_ids]

In [15]:
print(data)

[[ 7.02000000e+02  8.16000000e+02  4.26063991e+01  8.00000000e-01]
 [ 7.02000000e+02  8.88000000e+02  4.26063991e+01  8.50000000e-01]
 [ 7.02000000e+02  8.96000000e+02  4.26063991e+01  5.50000000e-01]
 ...
 [ 1.00100000e+03  9.51000000e+02 -3.73837195e+01  4.50000000e-01]
 [ 1.00100000e+03  7.00000000e+00 -4.67296494e+01  9.50000000e-01]
 [ 1.00100000e+03  2.39000000e+02 -4.67296494e+01  9.00000000e-01]]


In [16]:
print(data_ordered)

[[ 7.02000000e+02  9.23000000e+02  4.26063991e+01  5.00000000e-01]
 [ 7.02000000e+02  8.91000000e+02  4.26063991e+01  5.00000000e-01]
 [ 7.02000000e+02  1.05000000e+02  1.70515612e+01  4.00000000e-01]
 ...
 [ 1.00100000e+03  3.27000000e+02 -4.67296494e+01  7.50000000e-01]
 [ 1.00100000e+03  7.11000000e+02 -4.67296494e+01  2.50000000e-01]
 [ 1.00100000e+03  7.19000000e+02 -4.67296494e+01  5.50000000e-01]]


In [17]:
print(np.unique(data[:,1]))

print(np.size(np.unique(data[:,1])))

[   2.    3.    4. ... 1000. 1001. 1012.]
1001
